In [214]:
# import dependencies
import pandas as pd
from sodapy import Socrata
import os
import requests
import googlemaps
from datetime import datetime
from config import gkey
import gmaps
import pymongo

# establish connection with Google Maps API
goog_maps = googlemaps.Client(key=gkey)

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
cms_client = Socrata("data.cms.gov", "zJczdf3uI6etj0TLR11GyFlB2")

In [215]:
cdc_client = Socrata("data.cdc.gov", "zJczdf3uI6etj0TLR11GyFlB2"
cdc_results = cdc_client.get("a3uk-kgrx", limit=2000000)

# Convert to pandas DataFrame
cdc_results_df = pd.DataFrame.from_records(cdc_results)

SyntaxError: invalid syntax (<ipython-input-215-9ad34640c452>, line 2)

In [216]:
cdc_results_df

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
0,1411,NaN,Number of Drug Overdose Deaths,September,100,0.209391925847339,1468,NJ,NJ,2015
1,97.9872881355932,NaN,Percent with drugs specified,November,100,0.040500736377025,NaN,YC,YC,2015
2,6674,NaN,Number of Deaths,July,100,0.164818699430626,NaN,ND,ND,2016
3,64,NaN,Heroin (T40.1),January,100,0.0267343937976206,65,SC,SC,2015
4,684,NaN,"Opioids (T40.0-T40.4,T40.6)",May,100,0.00749105755004963,688,WA,WA,2015
5,11342,NaN,Number of Deaths,January,100,0.0440839358137895,NaN,NH,NH,2015
6,7899,NaN,Number of Deaths,July,100,0.063299151791366,NaN,SD,SD,2015
7,4358,NaN,Number of Drug Overdose Deaths,November,100,0.301462317210349,4608,PA,PA,2016
8,543,Underreported due to incomplete data,Number of Drug Overdose Deaths,January,100,0.0466789313270546,545,OR,OR,2018
9,2773,NaN,Number of Drug Overdose Deaths,November,100,0.173351234291652,2867,TX,TX,2016
10,1137,NaN,Number of Drug Overdose Deaths,March,100,0.005480352934729,1142,WA,WA,2016
11,54629,NaN,Number of Deaths,December,100,0.00549158871661572,NaN,WA,WA,2015
12,413,NaN,"Opioids (T40.0-T40.4,T40.6)",September,100,0.118895966029724,424,NH,NH,2015
13,61135,NaN,Number of Deaths,June,100,0.0245358632534555,NaN,MO,MO,2016
14,1796,NaN,Number of Drug Overdose Deaths,January,100,0.045028625340395,1816,MI,MI,2015
15,38075,NaN,Number of Deaths,November,100,0.0262639527248851,NaN,CO,CO,2016
16,95.4365079365079,Underreported due to incomplete data,Percent with drugs specified,January,100,0.0738794943359054,NaN,OR,OR,2017
17,67019,Underreported due to incomplete data,Number of Deaths,August,100,0.0373028544144198,NaN,VA,VA,2017
18,51,NaN,Cocaine (T40.5),July,100,0,53,ME,ME,2016
19,29667,NaN,Number of Deaths,August,100,0.010112245929821,NaN,IA,IA,2015
20,3398,NaN,Number of Drug Overdose Deaths,January,100,0.0256344527044348,3425,OH,OH,2016
21,7028,NaN,Number of Deaths,September,100,0.284575981787137,NaN,ND,ND,2015
22,354,NaN,Natural & semi-synthetic opioids (T40.2),July,100,0.0558743257473191,360,SC,SC,2016
23,40,NaN,"Synthetic opioids, excl. methadone (T40.4)",September,100,0.0590767153346274,41,OR,OR,2016
24,5777,NaN,Psychostimulants with abuse potential (T43.6),December,100,0.153226512564574,6008,US,US,2015
25,220,Underreported due to incomplete data,Natural & semi-synthetic opioids (T40.2),February,100,0,221,NV,NV,2017
26,449,NaN,Number of Drug Overdose Deaths,October,100,0.12709710218607,461,NH,NH,2015
27,1723,NaN,Number of Drug Overdose Deaths,December,100,0.813464712989908,2005,MA,MA,2015
28,63,NaN,Methadone (T40.3),September,100,0.0183040033470178,64,OK,OK,2015
29,62,NaN,"Synthetic opioids, excl. methadone (T40.4)",February,100,0.338477425276806,67,UT,UT,2015
...,...,...,...,...,...,...,...,...,...,...
10344,102,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.00509087206638497,103,OK,OK,2017
10345,14,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),November,100,0.0159821000479463,15,DC,DC,2017
10346,18360,Underreported due to incomplete data,Number of Deaths,August,100,0.669934640522876,NaN,UT,UT,2017
10347,677,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.0190918636840933,685,CT,CT,2017
10348,406,Underreported due to incomplete data,"Opioids (T40.0-T40.4,T40.6)",May,100,0.0661047760700711,411,NH,NH,2017
10349,38236,Underreported due to incomplete data,Number of Deaths,January,100,0.0313840359870279,NaN,CO,CO,2017
10350,106,Underreported due to incomplete data,Cocaine (T40.5),February,100,0.192086054552439,110,RI,RI,2018
10351,429,Underreported due to incomplete data,"Opioids (T40.0-T40.4,T40.6)",November,100,0.024358557973368,434,NH,NH,2017
10352,349,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),February,100,0.0320907097395304,353,WA,WA,2017
10353,2640,Underreported due to incomplete data,Number of Drug Overdose Deaths,January,100,0.0816351837308312,2665,MI,MI,2018
10354,243,Underreported due to incomplete data,Heroin (T40.1),February,100,0.152973994420948,249,WV,WV,2017
10355,31,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),September,100,0.0158503724837534,32,CT,CT,2017
10356,140,Underreported due to incomplete data,Heroin (T40.1),January,100,0.176347404386642,144,NM,NM,2018
10357,99673,Underreported due to incomplete data,Number of Deaths,August,100,0.492610837438424,NaN,NY,NY,2017
10358,1629,Underreported due to incomplete data,Number of Drug Overdose Deaths,February,100,0.00771807418612908,1630,IN,IN,2017
10359,79,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",April,100,0.0674498341858243,81,NM,NM,2017
10360,64,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.0352057580973244,65,NV,NV,2017
10361,12,Underreported due to incomplete data,Methadone (T40.3),January,100,0.0161851582099215,12,NH,NH,2018
10362,10101,Underreported due to incomplete data,Number of Deaths,February,100,0.0297000297000297,NaN,MT,MT,2018
10363,99.4623655913979,Underreported due to incomplete data,Percent with drugs specified,May,100,0.0184522271838211,NaN,YC,YC,2017
10364,1060,Underreported due to incomplete data,Number of Drug Overdose Deaths,July,100,0.0587418562426573,1077,WA,WA,2017
10365,267350,Underreported due to incomplete data,Number of Deaths,August,100,0.35459135964092,NaN,CA,CA,2017
10366,286,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),May,100,0.00517022981671535,287,OK,OK,2017
10367,94.5397815912636,Underreported due to incomplete data,Percent with drugs specified,January,100,0.888434202024553,NaN,UT,UT,2017
10368,95.9016393442623,Underreported due to incomplete data,Percent with drugs specified,February,100,0.0150138878462578,NaN,OK,OK,2018
10369,9,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),September,100,0,10,VT,VT,2017
10370,48,Underreported due to incomplete data,Methadone (T40.3),February,100,0.202095410306866,50,UT,UT,2018
10371,6227,Underreported due to incomplete data,Number of Deaths,March,100,0,NaN,DC,DC,2017
10372,542,Underreported due to incomplete data,Cocaine (T40.5),February,100,0.0386008124551955,559,YC,YC,2017
10373,1083,Underreported due to incomplete data,Number of Drug Overdose Deaths,September,100,0.0158503724837534,1096,CT,CT,2017

In [217]:
unique_indicator = cdc_results_df["indicator"].unique()

unique_indicator

array(['Number of Drug Overdose Deaths', 'Percent with drugs specified',
       'Number of Deaths', 'Heroin (T40.1)',
       'Opioids (T40.0-T40.4,T40.6)', 'Cocaine (T40.5)',
       'Natural & semi-synthetic opioids (T40.2)',
       'Synthetic opioids, excl. methadone (T40.4)',
       'Psychostimulants with abuse potential (T43.6)',
       'Methadone (T40.3)'], dtype=object)

In [218]:
overdoses_2016_df = cdc_results_df.loc[cdc_results_df["year"] == "2016", :]

overdoses_2016_df

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
2,6674,NaN,Number of Deaths,July,100,0.164818699430626,NaN,ND,ND,2016
7,4358,NaN,Number of Drug Overdose Deaths,November,100,0.301462317210349,4608,PA,PA,2016
9,2773,NaN,Number of Drug Overdose Deaths,November,100,0.173351234291652,2867,TX,TX,2016
10,1137,NaN,Number of Drug Overdose Deaths,March,100,0.005480352934729,1142,WA,WA,2016
13,61135,NaN,Number of Deaths,June,100,0.0245358632534555,NaN,MO,MO,2016
15,38075,NaN,Number of Deaths,November,100,0.0262639527248851,NaN,CO,CO,2016
18,51,NaN,Cocaine (T40.5),July,100,0,53,ME,ME,2016
20,3398,NaN,Number of Drug Overdose Deaths,January,100,0.0256344527044348,3425,OH,OH,2016
22,354,NaN,Natural & semi-synthetic opioids (T40.2),July,100,0.0558743257473191,360,SC,SC,2016
23,40,NaN,"Synthetic opioids, excl. methadone (T40.4)",September,100,0.0590767153346274,41,OR,OR,2016
34,80430,NaN,Number of Deaths,May,100,0.0671391271913465,NaN,GA,GA,2016
38,14410,NaN,Heroin (T40.1),June,100,0.154681724815674,14807,US,US,2016
41,18457,NaN,Number of Deaths,October,100,0.828953784472016,NaN,UT,UT,2016
42,454,NaN,"Opioids (T40.0-T40.4,T40.6)",April,100,0,456,NV,NV,2016
43,94,NaN,Cocaine (T40.5),March,100,0,98,RI,RI,2016
44,37894,NaN,Number of Deaths,August,100,0.0211115216129203,NaN,OK,OK,2016
45,9921,NaN,Number of Deaths,February,100,0.151194436044754,NaN,MT,MT,2016
49,86,NaN,Cocaine (T40.5),April,100,0.00547045951859956,89,WA,WA,2016
50,77,NaN,Methadone (T40.3),May,100,0.0201863354037267,78,VA,VA,2016
52,44225,NaN,Number of Deaths,October,100,0.0180893159977388,NaN,LA,LA,2016
53,93368,NaN,Number of Deaths,April,100,0.0417701996401337,NaN,MI,MI,2016
54,454,NaN,"Opioids (T40.0-T40.4,T40.6)",February,100,0.00418830624895292,457,NV,NV,2016
55,269,NaN,Natural & semi-synthetic opioids (T40.2),August,100,0,271,NV,NV,2016
57,393,NaN,Cocaine (T40.5),May,100,0.437244124532077,412,NY,NY,2016
60,381,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.33683265031157,412,UT,UT,2016
61,346,NaN,Natural & semi-synthetic opioids (T40.2),August,100,0.0559235997590983,352,SC,SC,2016
62,71016,NaN,Number of Deaths,November,100,0.19150613946153,NaN,TN,TN,2016
64,13228,NaN,Number of Deaths,July,100,0.0453583308134261,NaN,ID,ID,2016
68,45,NaN,Psychostimulants with abuse potential (T43.6),January,100,0.408054734559884,50,NY,NY,2016
70,4768,NaN,Number of Drug Overdose Deaths,March,100,0.371438626556905,5105,CA,CA,2016
...,...,...,...,...,...,...,...,...,...,...
7047,804,NaN,Number of Drug Overdose Deaths,June,100,0.0582838640043173,815,SC,SC,2016
7048,64,NaN,Psychostimulants with abuse potential (T43.6),August,100,0.0373936617743292,66,YC,YC,2016
7049,834,NaN,"Opioids (T40.0-T40.4,T40.6)",November,100,0.0165049184657028,840,CT,CT,2016
7050,170,NaN,"Synthetic opioids, excl. methadone (T40.4)",June,100,0.0582838640043173,174,SC,SC,2016
7052,62,NaN,Number of Drug Overdose Deaths,January,100,0.148060408646728,64,ND,ND,2016
7055,98.5239852398524,NaN,Percent with drugs specified,February,100,0,NaN,ME,ME,2016
7056,56648,NaN,Number of Deaths,June,100,0.26126253354046,NaN,AZ,AZ,2016
7058,164,NaN,Heroin (T40.1),July,100,0.569846955389124,182,UT,UT,2016
7059,80602,NaN,Number of Deaths,July,100,0.075680504205851,NaN,GA,GA,2016
7060,341,NaN,Number of Drug Overdose Deaths,November,100,0,343,ME,ME,2016
7061,2812,NaN,Number of Drug Overdose Deaths,December,100,0.17347300133954,2907,TX,TX,2016
7062,98.6798679867987,NaN,Percent with drugs specified,May,100,0,NaN,ME,ME,2016
7065,142,NaN,Natural & semi-synthetic opioids (T40.2),February,100,0.0253857219417257,144,OR,OR,2016
7066,1963,NaN,Number of Drug Overdose Deaths,February,100,0.0342586744034173,1982,MI,MI,2016
7067,689,NaN,Number of Drug Overdose Deaths,March,100,0.0041734485205125,692,NV,NV,2016
7069,93,NaN,Cocaine (T40.5),September,100,0.0146565780554385,97,WA,WA,2016
7073,29,NaN,Methadone (T40.3),July,100,0.0300812192920886,30,RI,RI,2016
7075,65,NaN,Number of Drug Overdose Deaths,July,100,0.164818699430626,68,ND,ND,2016
7078,7847,NaN,Number of Deaths,April,100,0.0254874474321397,NaN,SD,SD,2016
7079,21817,NaN,Number of Deaths,June,100,0.0962552138240821,NaN,WV,WV,2016
7084,591,NaN,"Synthetic opioids, excl. methadone (T40.4)",December,100,0.260536398467433,628,NC,NC,2016
7090,158,NaN,Natural & semi-synthetic opioids (T40.2),August,100,0.0679848167242649,162,NM,NM,2016
7092,273,NaN,"Synthetic opioids, excl. methadone (T40.4)",May,100,0.128931252014551,283,WV,WV,2016
7094,52,NaN,Heroin (T40.1),October,100,0.015770797739519,53,OK,OK,2016
7096,308,NaN,Natural & semi-synthetic opioids (T40.2),August,100,0.00915248032216731,311,WA,WA,2016
7100,246,NaN,"Opioids (T40.0-T40.4,T40.6)",April,100,0,247,ME,ME,2016
7104,890,NaN,Number of Drug Overdose Deaths,January,100,0.0827681342683067,906,LA,LA,2016
7106,326,NaN,Heroin (T40.1),June,100,0.00548295714155168,327,WA,WA,2016
7107,45,NaN,Heroin (T40.1),February,100,0,46,RI,RI,2016
7108,124,NaN,Methadone (T40.3),June,100,0.46476638018096,138,NY,NY,2016

In [219]:
overdoses_2016_df["data_value"] = overdoses_2016_df["data_value"].astype(float)

/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [220]:
unique_states = overdoses_2016_df.state.unique()

unique_states

array(['ND', 'PA', 'TX', 'WA', 'MO', 'CO', 'ME', 'OH', 'SC', 'OR', 'GA',
       'US', 'UT', 'NV', 'RI', 'OK', 'MT', 'VA', 'LA', 'MI', 'NY', 'TN',
       'ID', 'CA', 'WY', 'CT', 'NM', 'SD', 'AR', 'DC', 'VT', 'DE', 'IN',
       'WV', 'NH', 'MD', 'IA', 'NC', 'AK', 'NJ', 'KY', 'MS', 'YC', 'HI',
       'FL', 'IL', 'NE', 'MN', 'WI', 'AZ', 'AL', 'MA', 'KS'], dtype=object)

In [221]:
MA_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == "MA", :]

MA_2016_df = MA_2016.groupby("indicator").sum()

MA_2016_df.rename(columns={"data_value": "MA"})

                                      MA
indicator
Number of Deaths                686740.0
Number of Drug Overdose Deaths   23951.0

In [222]:
TX_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == "TX", :]
TX_2016_df = TX_2016.groupby("indicator").sum()

TX_2016_df

                                data_value
indicator
Number of Deaths                 2308662.0
Number of Drug Overdose Deaths     32557.0

In [223]:
TX_dict = TX_2016_df.to_dict()

TX_final_dict = TX_dict['data_value'] 

TX_final_dict["state"] = "TX"

TX_final_dict

{'Number of Deaths': 2308662.0,
 'Number of Drug Overdose Deaths': 32557.0,
 'state': 'TX'}

In [224]:
CA_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == "CA", :]
CA_2016_df = CA_2016.groupby("indicator").sum()

CA_2016_df

                                data_value
indicator
Number of Deaths                 3139581.0
Number of Drug Overdose Deaths     57154.0

In [225]:
CA_dict = CA_2016_df.to_dict()

CA_final_dict = CA_dict['data_value'] 

CA_final_dict["state"] = "CA"

CA_final_dict

{'Number of Deaths': 3139581.0,
 'Number of Drug Overdose Deaths': 57154.0,
 'state': 'CA'}

In [226]:
WA_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == "WA", :]
WA_2016_df = WA_2016.groupby("indicator").sum()

WA_2016_df

                                                  data_value
indicator
Cocaine (T40.5)                                  1037.000000
Heroin (T40.1)                                   3833.000000
Methadone (T40.3)                                1511.000000
Natural & semi-synthetic opioids (T40.2)         3490.000000
Number of Deaths                               656102.000000
Number of Drug Overdose Deaths                  13830.000000
Opioids (T40.0-T40.4,T40.6)                      8894.000000
Percent with drugs specified                     1128.353235
Psychostimulants with abuse potential (T43.6)    3900.000000
Synthetic opioids, excl. methadone (T40.4)        935.000000

In [227]:
WA_dict = WA_2016_df.to_dict()

WA_final_dict = WA_dict['data_value'] 

WA_final_dict["state"] = "WA"

WA_final_dict

{'Cocaine (T40.5)': 1037.0,
 'Heroin (T40.1)': 3833.0,
 'Methadone (T40.3)': 1511.0,
 'Natural & semi-synthetic opioids (T40.2)': 3490.0,
 'Number of Deaths': 656102.0,
 'Number of Drug Overdose Deaths': 13830.0,
 'Opioids (T40.0-T40.4,T40.6)': 8894.0,
 'Percent with drugs specified': 1128.3532349866266,
 'Psychostimulants with abuse potential (T43.6)': 3900.0,
 'Synthetic opioids, excl. methadone (T40.4)': 935.0,
 'state': 'WA'}

In [228]:
FL_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == "FL", :]
FL_2016_df = FL_2016.groupby("indicator").sum()
FL_dict = FL_2016_df.to_dict()
FL_final_dict = FL_dict['data_value'] 
FL_final_dict["state"] = "FL"

FL_final_dict

{'Number of Deaths': 2360692.0,
 'Number of Drug Overdose Deaths': 48380.0,
 'state': 'FL'}

In [229]:
states_combined = [TX_final_dict, CA_final_dict, WA_final_dict]

In [230]:
pd.DataFrame(states_combined)

,Cocaine (T40.5),Heroin (T40.1),Methadone (T40.3),Natural & semi-synthetic opioids (T40.2),Number of Deaths,Number of Drug Overdose Deaths,"Opioids (T40.0-T40.4,T40.6)",Percent with drugs specified,Psychostimulants with abuse potential (T43.6),"Synthetic opioids, excl. methadone (T40.4)",state
0,NaN,NaN,NaN,NaN,2308662.0,32557.0,NaN,NaN,NaN,NaN,TX
1,NaN,NaN,NaN,NaN,3139581.0,57154.0,NaN,NaN,NaN,NaN,CA
2,1037.0,3833.0,1511.0,3490.0,656102.0,13830.0,8894.0,1128.353235,3900.0,935.0,WA

In [231]:
for state in unique_states:
    state_2016 = overdoses_2016_df.loc[overdoses_2016_df["state_name"] == state, :]
    state_2016_df = state_2016.groupby("indicator").sum()
    state_2016_df.rename(columns={"data_value": state})
    print(state)
    print(state_2016_df)
    print("--------------------")

ND
                                data_value
indicator
Number of Deaths                   80487.0
Number of Drug Overdose Deaths       828.0
--------------------
PA
                                data_value
indicator
Number of Deaths                 1586270.0
Number of Drug Overdose Deaths     45980.0
--------------------
TX
                                data_value
indicator
Number of Deaths                 2308662.0
Number of Drug Overdose Deaths     32557.0
--------------------
WA
                                                  data_value
indicator
Cocaine (T40.5)                                  1037.000000
Heroin (T40.1)                                   3833.000000
Methadone (T40.3)                                1511.000000
Natural & semi-synthetic opioids (T40.2)         3490.000000
Number of Deaths                               656102.000000
Number of Drug Overdose Deaths                  13830.000000
Opioids (T40.0-T40.4,T40.6)                      8894.000000
Percent with drugs specified                     1128.353235
Psychostimulants with abuse potential (T43.6)    3900.000000
Synthetic opioids, excl. methadone (T40.4)        935.000000
--------------------
MO
                                data_value
indicator
Number of Deaths                  735070.0
Number of Drug Overdose Deaths     14478.0
--------------------
CO
                                data_value
indicator
Number of Deaths                  450894.0
Number of Drug Overdose Deaths     11137.0
--------------------
ME
                                                  data_value
indicator
Cocaine (T40.5)                                   555.000000
Heroin (T40.1)                                    632.000000
Methadone (T40.3)                                 406.000000
Natural & semi-synthetic opioids (T40.2)         1419.000000
Number of Deaths                               167830.000000
Number of Drug Overdose Deaths                   3796.000000
Opioids (T40.0-T40.4,T40.6)                      3222.000000
Percent with drugs specified                     1186.476283
Psychostimulants with abuse potential (T43.6)     331.000000
Synthetic opioids, excl. methadone (T40.4)       1852.000000
--------------------
OH
                                data_value
indicator
Number of Deaths                 1415504.0
Number of Drug Overdose Deaths     45503.0
--------------------
SC
                                                  data_value
indicator
Cocaine (T40.5)                                  1503.000000
Heroin (T40.1)                                   1283.000000
Methadone (T40.3)                                 694.000000
Natural & semi-synthetic opioids (T40.2)         4046.000000
Number of Deaths                               558101.000000
Number of Drug Overdose Deaths                   9569.000000
Opioids (T40.0-T40.4,T40.6)                      6862.000000
Percent with drugs specified                     1159.716342
Psychostimulants with abuse potential (T43.6)    1342.000000
Synthetic opioids, excl. methadone (T40.4)       2140.000000
--------------------
OR
                                                  data_value
indicator
Cocaine (T40.5)                                   299.000000
Heroin (T40.1)                                   1381.000000
Methadone (T40.3)                                 618.000000
Natural & semi-synthetic opioids (T40.2)         1679.000000
Number of Deaths                               426884.000000
Number of Drug Overdose Deaths                   6002.000000
Opioids (T40.0-T40.4,T40.6)                      3863.000000
Percent with drugs specified                     1150.120035
Psychostimulants with abuse potential (T43.6)    1684.000000
Synthetic opioids, excl. methadone (T40.4)        468.000000
--------------------
GA
                                data_value
indicator
Number of Deaths                  969526.0
Number of Drug Overdose Deaths     15538.0
--------------------
US
                                                 data_value
indicator
Cocaine (T40.5)                                1.018600e+05
Heroin (T40.1)                                 1.731830e+05
Methadone (T40.3)                              4.006500e+04
Natural & semi-synthetic opioids (T40.2)       1.631380e+05
Number of Deaths                               3.258620e+07
Number of Drug Overdose Deaths                 6.966020e+05
Opioids (T40.0-T40.4,T40.6)                    4.523690e+05
Percent with drugs specified                   1.012882e+03
Psychostimulants with abuse potential (T43.6)  8.058900e+04
Synthetic opioids, excl. methadone (T40.4)     1.707760e+05
--------------------
UT
                                                  data_value
indicator
Cocaine (T40.5)                                   614.000000
Heroin (T40.1)                                   1864.000000
Methadone (T40.3)                                 561.000000
Natural & semi-synthetic opioids (T40.2)         4490.000000
Number of Deaths                               219344.000000
Number of Drug Overdose Deaths                   8333.000000
Opioids (T40.0-T40.4,T40.6)                      6005.000000
Percent with drugs specified                     1152.005336
Psychostimulants with abuse potential (T43.6)    1903.000000
Synthetic opioids, excl. methadone (T40.4)        970.000000
--------------------
NV
                                                  data_value
indicator
Cocaine (T40.5)                                   496.000000
Heroin (T40.1)                                   1124.000000
Methadone (T40.3)                                 693.000000
Natural & semi-synthetic opioids (T40.2)         3199.000000
Number of Deaths                               291104.000000
Number of Drug Overdose Deaths                   8457.000000
Opioids (T40.0-T40.4,T40.6)                      5388.000000
Percent with drugs specified                     1162.614108
Psychostimulants with abuse potential (T43.6)    2743.000000
Synthetic opioids, excl. methadone (T40.4)        548.000000
--------------------
RI
                                                  data_value
indicator
Cocaine (T40.5)                                  1217.000000
Heroin (T40.1)                                    435.000000
Methadone (T40.3)                                 346.000000
Natural & semi-synthetic opioids (T40.2)         1251.000000
Number of Deaths                               120927.000000
Number of Drug Overdose Deaths                   3978.000000
Opioids (T40.0-T40.4,T40.6)                      3341.000000
Percent with drugs specified                     1193.641977
Psychostimulants with abuse potential (T43.6)      87.000000
Synthetic opioids, excl. methadone (T40.4)       1948.000000
--------------------
OK
                                                  data_value
indicator
Cocaine (T40.5)                                   321.000000
Heroin (T40.1)                                    523.000000
Methadone (T40.3)                                 584.000000
Natural & semi-synthetic opioids (T40.2)         3304.000000
Number of Deaths                               455459.000000
Number of Drug Overdose Deaths                   8913.000000
Opioids (T40.0-T40.4,T40.6)                      4996.000000
Percent with drugs specified                     1153.520576
Psychostimulants with abuse potential (T43.6)    2709.000000
Synthetic opioids, excl. methadone (T40.4)       1128.000000
--------------------
MT
                                data_value
indicator
Number of Deaths                  118846.0
Number of Drug Overdose Deaths      1477.0
--------------------
VA
                                                 data_value
indicator
Cocaine (T40.5)                                  2681.00000
Heroin (T40.1)                                   4675.00000
Methadone (T40.3)                                 952.00000
Natural & semi-synthetic opioids (T40.2)         3767.00000
Number of Deaths                               775307.00000
Number of Drug Overdose Deaths                  14327.00000
Opioids (T40.0-T40.4,T40.6)                     11715.00000
Percent with drugs specified                     1183.86855
Psychostimulants with abuse potential (T43.6)     678.00000
Synthetic opioids, excl. methadone (T40.4)       5525.00000
--------------------
LA
                                data_value
indicator
Number of Deaths                  526179.0
Number of Drug Overdose Deaths     11393.0
--------------------
MI
                                data_value
indicator
Number of Deaths                 1123841.0
Number of Drug Overdose Deaths     24245.0
--------------------
NY
                                                 data_value
indicator
Cocaine (T40.5)                                5.208000e+03
Heroin (T40.1)                                 8.922000e+03
Methadone (T40.3)                              1.469000e+03
Natural & semi-synthetic opioids (T40.2)       6.499000e+03
Number of Deaths                               1.169431e+06
Number of Drug Overdose Deaths                 2.482000e+04
Opioids (T40.0-T40.4,T40.6)                    2.073300e+04
Percent with drugs specified                   1.150886e+03
Psychostimulants with abuse potential (T43.6)  7.970000e+02
Synthetic opioids, excl. methadone (T40.4)     9.955000e+03
--------------------
TN
                                data_value
indicator
Number of Deaths                  845502.0
Number of Drug Overdose Deaths     18632.0
--------------------
ID
                                data_value
indicator
Number of Deaths                  157810.0
Number of Drug Overdose Deaths      2623.0
--------------------
CA
                                data_value
indicator
Number of Deaths                 3139581.0
Number of Drug Overdose Deaths     57154.0
--------------------
WY
                                data_value
indicator
Number of Deaths                   52723.0
Number of Drug Overdose Deaths      1138.0
--------------------
CT
                                                  data_value
indicator
Cocaine (T40.5)                                  2424.000000
Heroin (T40.1)                                   5313.000000
Methadone (T40.3)                                 830.000000
Natural & semi-synthetic opioids (T40.2)         2280.000000
Number of Deaths                               362773.000000
Number of Drug Overdose Deaths                  10776.000000
Opioids (T40.0-T40.4,T40.6)                      9528.000000
Percent with drugs specified                     1195.997138
Psychostimulants with abuse potential (T43.6)     291.000000
Synthetic opioids, excl. methadone (T40.4)       4424.000000
--------------------
NM
                                                  data_value
indicator
Cocaine (T40.5)                                   632.000000
Heroin (T40.1)                                   1836.000000
Methadone (T40.3)                                 482.000000
Natural & semi-synthetic opioids (T40.2)         1943.000000
Number of Deaths                               209960.000000
Number of Drug Overdose Deaths                   5881.000000
Opioids (T40.0-T40.4,T40.6)                      4218.000000
Percent with drugs specified                     1174.256896
Psychostimulants with abuse potential (T43.6)    1458.000000
Synthetic opioids, excl. methadone (T40.4)        675.000000
--------------------
SD
                                data_value
indicator
Number of Deaths                   94162.0
Number of Drug Overdose Deaths       809.0
--------------------
AR
                                data_value
indicator
Number of Deaths                  366574.0
Number of Drug Overdose Deaths      4513.0
--------------------
DC
                                                 data_value
indicator
Cocaine (T40.5)                                  784.000000
Heroin (T40.1)                                  1334.000000
Methadone (T40.3)                                178.000000
Natural & semi-synthetic opioids (T40.2)         399.000000
Number of Deaths                               69250.000000
Number of Drug Overdose Deaths                  2586.000000
Opioids (T40.0-T40.4,T40.6)                     1989.000000
Percent with drugs specified                    1193.268011
Psychostimulants with abuse potential (T43.6)     50.000000
Synthetic opioids, excl. methadone (T40.4)       985.000000
--------------------
VT
                                                 data_value
indicator
Cocaine (T40.5)                                  206.000000
Heroin (T40.1)                                   482.000000
Methadone (T40.3)                                122.000000
Natural & semi-synthetic opioids (T40.2)         289.000000
Number of Deaths                               68688.000000
Number of Drug Overdose Deaths                  1363.000000
Opioids (T40.0-T40.4,T40.6)                     1078.000000
Percent with drugs specified                    1171.413902
Psychostimulants with abuse potential (T43.6)     13.000000
Synthetic opioids, excl. methadone (T40.4)       484.000000
--------------------
DE
                                data_value
indicator
Number of Deaths                  103860.0
Number of Drug Overdose Deaths      2724.0
--------------------
IN
                                data_value
indicator
Number of Deaths                  755967.0
Number of Drug Overdose Deaths     16365.0
--------------------
WV
                                                  data_value
indicator
Cocaine (T40.5)                                  1474.000000
Heroin (T40.1)                                   2716.000000
Methadone (T40.3)                                 363.000000
Natural & semi-synthetic opioids (T40.2)         4140.000000
Number of Deaths                               262060.000000
Number of Drug Overdose Deaths                   9617.000000
Opioids (T40.0-T40.4,T40.6)                      8172.000000
Percent with drugs specified                     1186.039749
Psychostimulants with abuse potential (T43.6)     949.000000
Synthetic opioids, excl. methadone (T40.4)       3746.000000
--------------------
NH
                                                  data_value
indicator
Cocaine (T40.5)                                   551.000000
Heroin (T40.1)                                    598.000000
Methadone (T40.3)                                 336.000000
Natural & semi-synthetic opioids (T40.2)          843.000000
Number of Deaths                               139496.000000
Number of Drug Overdose Deaths                   5256.000000
Opioids (T40.0-T40.4,T40.6)                      4758.000000
Percent with drugs specified                     1190.166289
Psychostimulants with abuse potential (T43.6)      90.000000
Synthetic opioids, excl. methadone (T40.4)       3730.000000
--------------------
MD
                                                  data_value
indicator
Cocaine (T40.5)                                  2716.000000
Heroin (T40.1)                                   6530.000000
Methadone (T40.3)                                2214.000000
Natural & semi-synthetic opioids (T40.2)         6560.000000
Number of Deaths                               568857.000000
Number of Drug Overdose Deaths                  20291.000000
Opioids (T40.0-T40.4,T40.6)                     17918.000000
Percent with drugs specified                     1185.144606
Psychostimulants with abuse potential (T43.6)     392.000000
Synthetic opioids, excl. methadone (T40.4)       8772.000000
--------------------
IA
                                data_value
indicator
Number of Deaths                  347398.0
Number of Drug Overdose Deaths      3725.0
--------------------
NC
                                                 data_value
indicator
Cocaine (T40.5)                                5.034000e+03
Heroin (T40.1)                                 5.666000e+03
Methadone (T40.3)                              1.346000e+03
Natural & semi-synthetic opioids (T40.2)       7.133000e+03
Number of Deaths                               1.082087e+06
Number of Drug Overdose Deaths                 2.136100e+04
Opioids (T40.0-T40.4,T40.6)                    1.634300e+04
Percent with drugs specified                   1.147838e+03
Psychostimulants with abuse potential (T43.6)  1.081000e+03
Synthetic opioids, excl. methadone (T40.4)     5.582000e+03
--------------------
AK
                                data_value
indicator
Number of Deaths                   51141.0
Number of Drug Overdose Deaths      1594.0
--------------------
NJ
                                data_value
indicator
Number of Deaths                  846797.0
Number of Drug Overdose Deaths     20055.0
--------------------
KY
                                data_value
indicator
Number of Deaths                  559117.0
Number of Drug Overdose Deaths     16155.0
--------------------
MS
                                data_value
indicator
Number of Deaths                  369589.0
Number of Drug Overdose Deaths      3933.0
--------------------

YC
                                                  data_value
indicator
Cocaine (T40.5)                                  4753.000000
Heroin (T40.1)                                   6026.000000
Methadone (T40.3)                                1773.000000
Natural & semi-synthetic opioids (T40.2)         3429.000000
Number of Deaths                               643266.000000
Number of Drug Overdose Deaths                  14518.000000
Opioids (T40.0-T40.4,T40.6)                     11342.000000
Percent with drugs specified                     1187.322417
Psychostimulants with abuse potential (T43.6)     715.000000
Synthetic opioids, excl. methadone (T40.4)       4436.000000
--------------------
HI
                                data_value
indicator
Number of Deaths                  131591.0
Number of Drug Overdose Deaths      2294.0
--------------------
FL
                                data_value
indicator
Number of Deaths                 2360692.0
Number of Drug Overdose Deaths     48380.0
--------------------
IL
                                data_value
indicator
Number of Deaths                 1240690.0
Number of Drug Overdose Deaths     26227.0
--------------------
NE
                                data_value
indicator
Number of Deaths                  196435.0
Number of Drug Overdose Deaths      1425.0
--------------------
MN
                                data_value
indicator
Number of Deaths                  512281.0
Number of Drug Overdose Deaths      7668.0
--------------------
WI
                                data_value
indicator
Number of Deaths                  612995.0
Number of Drug Overdose Deaths     11926.0
--------------------
AZ
                                data_value
indicator
Number of Deaths                  679217.0
Number of Drug Overdose Deaths     16403.0
--------------------
AL
                                data_value
indicator
Number of Deaths                  608611.0
Number of Drug Overdose Deaths      8324.0
--------------------
MA
                                data_value
indicator
Number of Deaths                  686740.0
Number of Drug Overdose Deaths     23951.0
--------------------
KS
                                data_value
indicator
Number of Deaths                  304518.0
Number of Drug Overdose Deaths      3774.0
--------------------

In [232]:
state_dicts = []

In [233]:
for state in unique_states:
    
    State_2016 = overdoses_2016_df.loc[overdoses_2016_df["state"] == state, :]
    State_2016_df = State_2016.groupby("indicator").sum()
    state_dict = State_2016_df.to_dict()
    state_final_dict = state_dict['data_value'] 
    state_final_dict["State"] = state
    state_dicts.append(state_final_dict)

In [234]:
state_dicts

[{'Number of Deaths': 80487.0,
  'Number of Drug Overdose Deaths': 828.0,
  'State': 'ND'},
 {'Number of Deaths': 1586270.0,
  'Number of Drug Overdose Deaths': 45980.0,
  'State': 'PA'},
 {'Number of Deaths': 2308662.0,
  'Number of Drug Overdose Deaths': 32557.0,
  'State': 'TX'},
 {'Cocaine (T40.5)': 1037.0,
  'Heroin (T40.1)': 3833.0,
  'Methadone (T40.3)': 1511.0,
  'Natural & semi-synthetic opioids (T40.2)': 3490.0,
  'Number of Deaths': 656102.0,
  'Number of Drug Overdose Deaths': 13830.0,
  'Opioids (T40.0-T40.4,T40.6)': 8894.0,
  'Percent with drugs specified': 1128.3532349866266,
  'Psychostimulants with abuse potential (T43.6)': 3900.0,
  'Synthetic opioids, excl. methadone (T40.4)': 935.0,
  'State': 'WA'},
 {'Number of Deaths': 735070.0,
  'Number of Drug Overdose Deaths': 14478.0,
  'State': 'MO'},
 {'Number of Deaths': 450894.0,
  'Number of Drug Overdose Deaths': 11137.0,
  'State': 'CO'},
 {'Cocaine (T40.5)': 555.0,
  'Heroin (T40.1)': 632.0,
  'Methadone (T40.3)': 406.0,
  'Natural & semi-synthetic opioids (T40.2)': 1419.0,
  'Number of Deaths': 167830.0,
  'Number of Drug Overdose Deaths': 3796.0,
  'Opioids (T40.0-T40.4,T40.6)': 3222.0,
  'Percent with drugs specified': 1186.476283404314,
  'Psychostimulants with abuse potential (T43.6)': 331.0,
  'Synthetic opioids, excl. methadone (T40.4)': 1852.0,
  'State': 'ME'},
 {'Number of Deaths': 1415504.0,
  'Number of Drug Overdose Deaths': 45503.0,
  'State': 'OH'},
 {'Cocaine (T40.5)': 1503.0,
  'Heroin (T40.1)': 1283.0,
  'Methadone (T40.3)': 694.0,
  'Natural & semi-synthetic opioids (T40.2)': 4046.0,
  'Number of Deaths': 558101.0,
  'Number of Drug Overdose Deaths': 9569.0,
  'Opioids (T40.0-T40.4,T40.6)': 6862.0,
  'Percent with drugs specified': 1159.716341701506,
  'Psychostimulants with abuse potential (T43.6)': 1342.0,
  'Synthetic opioids, excl. methadone (T40.4)': 2140.0,
  'State': 'SC'},
 {'Cocaine (T40.5)': 299.0,
  'Heroin (T40.1)': 1381.0,
  'Methadone (T40.3)': 618.0,
  'Natural & semi-synthetic opioids (T40.2)': 1679.0,
  'Number of Deaths': 426884.0,
  'Number of Drug Overdose Deaths': 6002.0,
  'Opioids (T40.0-T40.4,T40.6)': 3863.0,
  'Percent with drugs specified': 1150.1200346702324,
  'Psychostimulants with abuse potential (T43.6)': 1684.0,
  'Synthetic opioids, excl. methadone (T40.4)': 468.0,
  'State': 'OR'},
 {'Number of Deaths': 969526.0,
  'Number of Drug Overdose Deaths': 15538.0,
  'State': 'GA'},
 {'Cocaine (T40.5)': 101860.0,
  'Heroin (T40.1)': 173183.0,
  'Methadone (T40.3)': 40065.0,
  'Natural & semi-synthetic opioids (T40.2)': 163138.0,
  'Number of Deaths': 32586196.0,
  'Number of Drug Overdose Deaths': 696602.0,
  'Opioids (T40.0-T40.4,T40.6)': 452369.0,
  'Percent with drugs specified': 1012.8824567445898,
  'Psychostimulants with abuse potential (T43.6)': 80589.0,
  'Synthetic opioids, excl. methadone (T40.4)': 170776.0,
  'State': 'US'},
 {'Cocaine (T40.5)': 614.0,
  'Heroin (T40.1)': 1864.0,
  'Methadone (T40.3)': 561.0,
  'Natural & semi-synthetic opioids (T40.2)': 4490.0,
  'Number of Deaths': 219344.0,
  'Number of Drug Overdose Deaths': 8333.0,
  'Opioids (T40.0-T40.4,T40.6)': 6005.0,
  'Percent with drugs specified': 1152.0053362742538,
  'Psychostimulants with abuse potential (T43.6)': 1903.0,
  'Synthetic opioids, excl. methadone (T40.4)': 970.0,
  'State': 'UT'},
 {'Cocaine (T40.5)': 496.0,
  'Heroin (T40.1)': 1124.0,
  'Methadone (T40.3)': 693.0,
  'Natural & semi-synthetic opioids (T40.2)': 3199.0,
  'Number of Deaths': 291104.0,
  'Number of Drug Overdose Deaths': 8457.0,
  'Opioids (T40.0-T40.4,T40.6)': 5388.0,
  'Percent with drugs specified': 1162.6141080963016,
  'Psychostimulants with abuse potential (T43.6)': 2743.0,
  'Synthetic opioids, excl. methadone (T40.4)': 548.0,
  'State': 'NV'},
 {'Cocaine (T40.5)': 1217.0,
  'Heroin (T40.1)': 435.0,
  'Methadone (T40.3)': 346.0,
  'Natural & semi-synthetic opioids (T40.2)': 1251.0,
  'Number of Deaths': 120927.0,
  'Number of Drug Overdose Deaths': 3978.0,
  'Opioids (T40.0-T40.4,T40.6)': 3341.0,
  'Percent with drugs specified': 1193.6419769288552,
  'Psychostimulants with abuse potential (T43.6)': 87.0,
  'Synthetic opioids, excl. methadone (T40.4)': 1948.0,
  'State': 'RI'},
 {'Cocaine (T40.5)': 321.0,
  'Heroin (T40.1)': 523.0,
  'Methadone (T40.3)': 584.0,
  'Natural & semi-synthetic opioids (T40.2)': 3304.0,
  'Number of Deaths': 455459.0,
  'Number of Drug Overdose Deaths': 8913.0,
  'Opioids (T40.0-T40.4,T40.6)': 4996.0,
  'Percent with drugs specified': 1153.5205759741195,
  'Psychostimulants with abuse potential (T43.6)': 2709.0,
  'Synthetic opioids, excl. methadone (T40.4)': 1128.0,
  'State': 'OK'},
 {'Number of Deaths': 118846.0,
  'Number of Drug Overdose Deaths': 1477.0,
  'State': 'MT'},
 {'Cocaine (T40.5)': 2681.0,
  'Heroin (T40.1)': 4675.0,
  'Methadone (T40.3)': 952.0,
  'Natural & semi-synthetic opioids (T40.2)': 3767.0,
  'Number of Deaths': 775307.0,
  'Number of Drug Overdose Deaths': 14327.0,
  'Opioids (T40.0-T40.4,T40.6)': 11715.0,
  'Percent with drugs specified': 1183.8685504651448,
  'Psychostimulants with abuse potential (T43.6)': 678.0,
  'Synthetic opioids, excl. methadone (T40.4)': 5525.0,
  'State': 'VA'},
 {'Number of Deaths': 526179.0,
  'Number of Drug Overdose Deaths': 11393.0,
  'State': 'LA'},
 {'Number of Deaths': 1123841.0,
  'Number of Drug Overdose Deaths': 24245.0,
  'State': 'MI'},
 {'Cocaine (T40.5)': 5208.0,
  'Heroin (T40.1)': 8922.0,
  'Methadone (T40.3)': 1469.0,
  'Natural & semi-synthetic opioids (T40.2)': 6499.0,
  'Number of Deaths': 1169431.0,
  'Number of Drug Overdose Deaths': 24820.0,
  'Opioids (T40.0-T40.4,T40.6)': 20733.0,
  'Percent with drugs specified': 1150.8862578264293,
  'Psychostimulants with abuse potential (T43.6)': 797.0,
  'Synthetic opioids, excl. methadone (T40.4)': 9955.0,
  'State': 'NY'},
 {'Number of Deaths': 845502.0,
  'Number of Drug Overdose Deaths': 18632.0,
  'State': 'TN'},
 {'Number of Deaths': 157810.0,
  'Number of Drug Overdose Deaths': 2623.0,
  'State': 'ID'},
 {'Number of Deaths': 3139581.0,
  'Number of Drug Overdose Deaths': 57154.0,
  'State': 'CA'},
 {'Number of Deaths': 52723.0,
  'Number of Drug Overdose Deaths': 1138.0,
  'State': 'WY'},
 {'Cocaine (T40.5)': 2424.0,
  'Heroin (T40.1)': 5313.0,
  'Methadone (T40.3)': 830.0,
  'Natural & semi-synthetic opioids (T40.2)': 2280.0,
  'Number of Deaths': 362773.0,
  'Number of Drug Overdose Deaths': 10776.0,
  'Opioids (T40.0-T40.4,T40.6)': 9528.0,
  'Percent with drugs specified': 1195.9971378036953,
  'Psychostimulants with abuse potential (T43.6)': 291.0,
  'Synthetic opioids, excl. methadone (T40.4)': 4424.0,
  'State': 'CT'},
 {'Cocaine (T40.5)': 632.0,
  'Heroin (T40.1)': 1836.0,
  'Methadone (T40.3)': 482.0,
  'Natural & semi-synthetic opioids (T40.2)': 1943.0,
  'Number of Deaths': 209960.0,
  'Number of Drug Overdose Deaths': 5881.0,
  'Opioids (T40.0-T40.4,T40.6)': 4218.0,
  'Percent with drugs specified': 1174.2568963768103,
  'Psychostimulants with abuse potential (T43.6)': 1458.0,
  'Synthetic opioids, excl. methadone (T40.4)': 675.0,
  'State': 'NM'},
 {'Number of Deaths': 94162.0,
  'Number of Drug Overdose Deaths': 809.0,
  'State': 'SD'},
 {'Number of Deaths': 366574.0,
  'Number of Drug Overdose Deaths': 4513.0,
  'State': 'AR'},
 {'Cocaine (T40.5)': 784.0,
  'Heroin (T40.1)': 1334.0,
  'Methadone (T40.3)': 178.0,
  'Natural & semi-synthetic opioids (T40.2)': 399.0,
  'Number of Deaths': 69250.0,
  'Number of Drug Overdose Deaths': 2586.0,
  'Opioids (T40.0-T40.4,T40.6)': 1989.0,
  'Percent with drugs specified': 1193.2680107363692,
  'Psychostimulants with abuse potential (T43.6)': 50.0,
  'Synthetic opioids, excl. methadone (T40.4)': 985.0,
  'State': 'DC'},
 {'Cocaine (T40.5)': 206.0,
  'Heroin (T40.1)': 482.0,
  'Methadone (T40.3)': 122.0,
  'Natural & semi-synthetic opioids (T40.2)': 289.0,
  'Number of Deaths': 68688.0,
  'Number of Drug Overdose Deaths': 1363.0,
  'Opioids (T40.0-T40.4,T40.6)': 1078.0,
  'Percent with drugs specified': 1171.4139022810702,
  'Psychostimulants with abuse potential (T43.6)': 13.0,
  'Synthetic opioids, excl. methadone (T40.4)': 484.0,
  'State': 'VT'},
 {'Number of Deaths': 103860.0,
  'Number of Drug Overdose Deaths': 2724.0,
  'State': 'DE'},
 {'Number of Deaths': 755967.0,
  'Number of Drug Overdose Deaths': 16365.0,
  'State': 'IN'},
 {'Cocaine (T40.5)': 1474.0,
  'Heroin (T40.1)': 2716.0,
  'Methadone (T40.3)': 363.0,
  'Natural & semi-synthetic opioids (T40.2)': 4140.0,
  'Number of Deaths': 262060.0,
  'Number of Drug Overdose Deaths': 9617.0,
  'Opioids (T40.0-T40.4,T40.6)': 8172.0,
  'Percent with drugs specified': 1186.0397492227148,
  'Psychostimulants with abuse potential (T43.6)': 949.0,
  'Synthetic opioids, excl. methadone (T40.4)': 3746.0,
  'State': 'WV'},
 {'Cocaine (T40.5)': 551.0,
  'Heroin (T40.1)': 598.0,
  'Methadone (T40.3)': 336.0,
  'Natural & semi-synthetic opioids (T40.2)': 843.0,
  'Number of Deaths': 139496.0,
  'Number of Drug Overdose Deaths': 5256.0,
  'Opioids (T40.0-T40.4,T40.6)': 4758.0,
  'Percent with drugs specified': 1190.1662892675763,
  'Psychostimulants with abuse potential (T43.6)': 90.0,
  'Synthetic opioids, excl. methadone (T40.4)': 3730.0,
  'State': 'NH'},
 {'Cocaine (T40.5)': 2716.0,
  'Heroin (T40.1)': 6530.0,
  'Methadone (T40.3)': 2214.0,
  'Natural & semi-synthetic opioids (T40.2)': 6560.0,
  'Number of Deaths': 568857.0,
  'Number of Drug Overdose Deaths': 20291.0,
  'Opioids (T40.0-T40.4,T40.6)': 17918.0,
  'Percent with drugs specified': 1185.144606002933,
  'Psychostimulants with abuse potential (T43.6)': 392.0,
  'Synthetic opioids, excl. methadone (T40.4)': 8772.0,
  'State': 'MD'},
 {'Number of Deaths': 347398.0,
  'Number of Drug Overdose Deaths': 3725.0,
  'State': 'IA'},
 {'Cocaine (T40.5)': 5034.0,
  'Heroin (T40.1)': 5666.0,
  'Methadone (T40.3)': 1346.0,
  'Natural & semi-synthetic opioids (T40.2)': 7133.0,
  'Number of Deaths': 1082087.0,
  'Number of Drug Overdose Deaths': 21361.0,
  'Opioids (T40.0-T40.4,T40.6)': 16343.0,
  'Percent with drugs specified': 1147.8375438109888,
  'Psychostimulants with abuse potential (T43.6)': 1081.0,
  'Synthetic opioids, excl. methadone (T40.4)': 5582.0,
  'State': 'NC'},
 {'Number of Deaths': 51141.0,
  'Number of Drug Overdose Deaths': 1594.0,
  'State': 'AK'},
 {'Number of Deaths': 846797.0,
  'Number of Drug Overdose Deaths': 20055.0,
  'State': 'NJ'},
 {'Number of Deaths': 559117.0,
  'Number of Drug Overdose Deaths': 16155.0,
  'State': 'KY'},
 {'Number of Deaths': 369589.0,
  'Number of Drug Overdose Deaths': 3933.0,
  'State': 'MS'},
 {'Cocaine (T40.5)': 4753.0,
  'Heroin (T40.1)': 6026.0,
  'Methadone (T40.3)': 1773.0,
  'Natural & semi-synthetic opioids (T40.2)': 3429.0,
  'Number of Deaths': 643266.0,
  'Number of Drug Overdose Deaths': 14518.0,
  'Opioids (T40.0-T40.4,T40.6)': 11342.0,
  'Percent with drugs specified': 1187.3224168666557,
  'Psychostimulants with abuse potential (T43.6)': 715.0,
  'Synthetic opioids, excl. methadone (T40.4)': 4436.0,
  'State': 'YC'},
 {'Number of Deaths': 131591.0,
  'Number of Drug Overdose Deaths': 2294.0,
  'State': 'HI'},
 {'Number of Deaths': 2360692.0,
  'Number of Drug Overdose Deaths': 48380.0,
  'State': 'FL'},
 {'Number of Deaths': 1240690.0,
  'Number of Drug Overdose Deaths': 26227.0,
  'State': 'IL'},
 {'Number of Deaths': 196435.0,
  'Number of Drug Overdose Deaths': 1425.0,
  'State': 'NE'},
 {'Number of Deaths': 512281.0,
  'Number of Drug Overdose Deaths': 7668.0,
  'State': 'MN'},
 {'Number of Deaths': 612995.0,
  'Number of Drug Overdose Deaths': 11926.0,
  'State': 'WI'},
 {'Number of Deaths': 679217.0,
  'Number of Drug Overdose Deaths': 16403.0,
  'State': 'AZ'},
 {'Number of Deaths': 608611.0,
  'Number of Drug Overdose Deaths': 8324.0,
  'State': 'AL'},
 {'Number of Deaths': 686740.0,
  'Number of Drug Overdose Deaths': 23951.0,
  'State': 'MA'},
 {'Number of Deaths': 304518.0,
  'Number of Drug Overdose Deaths': 3774.0,
  'State': 'KS'}]

In [235]:
total_df = pd.DataFrame(state_dicts)

total_df.head()

,Cocaine (T40.5),Heroin (T40.1),Methadone (T40.3),Natural & semi-synthetic opioids (T40.2),Number of Deaths,Number of Drug Overdose Deaths,"Opioids (T40.0-T40.4,T40.6)",Percent with drugs specified,Psychostimulants with abuse potential (T43.6),State,"Synthetic opioids, excl. methadone (T40.4)"
0,NaN,NaN,NaN,NaN,80487.0,828.0,NaN,NaN,NaN,ND,NaN
1,NaN,NaN,NaN,NaN,1586270.0,45980.0,NaN,NaN,NaN,PA,NaN
2,NaN,NaN,NaN,NaN,2308662.0,32557.0,NaN,NaN,NaN,TX,NaN
3,1037.0,3833.0,1511.0,3490.0,656102.0,13830.0,8894.0,1128.353235,3900.0,WA,935.0
4,NaN,NaN,NaN,NaN,735070.0,14478.0,NaN,NaN,NaN,MO,NaN

In [236]:
renamed = total_df.rename(columns={'Number of Deaths': 'Total Number of Deaths', 'Opioids (T40.0-T40.4,T40.6)': 'Opioid Overdose Deaths', 'Heroin (T40.1)': 'Heroin Overdose Deaths', 'Natural & semi-synthetic opioids (T40.2)': 'Natural & Semi-synthetic Opioid Overdose Deaths', 'Synthetic opioids, excl. methadone (T40.4)': 'Synthetic Opioid Deaths (excl. methadone)', 'Methadone (T40.3)': 'Methadone Overdose Deaths'})
                         
renamed.head()

,Cocaine (T40.5),Heroin Overdose Deaths,Methadone Overdose Deaths,Natural & Semi-synthetic Opioid Overdose Deaths,Total Number of Deaths,Number of Drug Overdose Deaths,Opioid Overdose Deaths,Percent with drugs specified,Psychostimulants with abuse potential (T43.6),State,Synthetic Opioid Deaths (excl. methadone)
0,NaN,NaN,NaN,NaN,80487.0,828.0,NaN,NaN,NaN,ND,NaN
1,NaN,NaN,NaN,NaN,1586270.0,45980.0,NaN,NaN,NaN,PA,NaN
2,NaN,NaN,NaN,NaN,2308662.0,32557.0,NaN,NaN,NaN,TX,NaN
3,1037.0,3833.0,1511.0,3490.0,656102.0,13830.0,8894.0,1128.353235,3900.0,WA,935.0
4,NaN,NaN,NaN,NaN,735070.0,14478.0,NaN,NaN,NaN,MO,NaN

In [237]:
renamed['% of Drug Overdose Deaths'] = (renamed['Number of Drug Overdose Deaths']/renamed['Total Number of Deaths'])*100
renamed = renamed[renamed.State != 'US']
renamed.head()

,Cocaine (T40.5),Heroin Overdose Deaths,Methadone Overdose Deaths,Natural & Semi-synthetic Opioid Overdose Deaths,Total Number of Deaths,Number of Drug Overdose Deaths,Opioid Overdose Deaths,Percent with drugs specified,Psychostimulants with abuse potential (T43.6),State,Synthetic Opioid Deaths (excl. methadone),% of Drug Overdose Deaths
0,NaN,NaN,NaN,NaN,80487.0,828.0,NaN,NaN,NaN,ND,NaN,1.028738
1,NaN,NaN,NaN,NaN,1586270.0,45980.0,NaN,NaN,NaN,PA,NaN,2.898624
2,NaN,NaN,NaN,NaN,2308662.0,32557.0,NaN,NaN,NaN,TX,NaN,1.410211
3,1037.0,3833.0,1511.0,3490.0,656102.0,13830.0,8894.0,1128.353235,3900.0,WA,935.0,2.107904
4,NaN,NaN,NaN,NaN,735070.0,14478.0,NaN,NaN,NaN,MO,NaN,1.969608

In [239]:
renamed_df = renamed[['State', 'Total Number of Deaths', 'Number of Drug Overdose Deaths', '% of Drug Overdose Deaths', 'Opioid Overdose Deaths', 'Heroin Overdose Deaths', 'Natural & Semi-synthetic Opioid Overdose Deaths', 'Synthetic Opioid Deaths (excl. methadone)', 'Methadone Overdose Deaths']]

Opioid_overdose_deaths_2016 = renamed_df.sort_values(by='Opioid Overdose Deaths', ascending=False)

Opioid_overdose_deaths_2016

,State,Total Number of Deaths,Number of Drug Overdose Deaths,% of Drug Overdose Deaths,Opioid Overdose Deaths,Heroin Overdose Deaths,Natural & Semi-synthetic Opioid Overdose Deaths,Synthetic Opioid Deaths (excl. methadone),Methadone Overdose Deaths
20,NY,1169431.0,24820.0,2.122400,20733.0,8922.0,6499.0,9955.0,1469.0
35,MD,568857.0,20291.0,3.566977,17918.0,6530.0,6560.0,8772.0,2214.0
37,NC,1082087.0,21361.0,1.974056,16343.0,5666.0,7133.0,5582.0,1346.0
17,VA,775307.0,14327.0,1.847913,11715.0,4675.0,3767.0,5525.0,952.0
42,YC,643266.0,14518.0,2.256920,11342.0,6026.0,3429.0,4436.0,1773.0
25,CT,362773.0,10776.0,2.970453,9528.0,5313.0,2280.0,4424.0,830.0
3,WA,656102.0,13830.0,2.107904,8894.0,3833.0,3490.0,935.0,1511.0
33,WV,262060.0,9617.0,3.669770,8172.0,2716.0,4140.0,3746.0,363.0
8,SC,558101.0,9569.0,1.714564,6862.0,1283.0,4046.0,2140.0,694.0
12,UT,219344.0,8333.0,3.799055,6005.0,1864.0,4490.0,970.0,561.0
13,NV,291104.0,8457.0,2.905147,5388.0,1124.0,3199.0,548.0,693.0
15,OK,455459.0,8913.0,1.956927,4996.0,523.0,3304.0,1128.0,584.0
34,NH,139496.0,5256.0,3.767850,4758.0,598.0,843.0,3730.0,336.0
26,NM,209960.0,5881.0,2.801010,4218.0,1836.0,1943.0,675.0,482.0
9,OR,426884.0,6002.0,1.406003,3863.0,1381.0,1679.0,468.0,618.0
14,RI,120927.0,3978.0,3.289588,3341.0,435.0,1251.0,1948.0,346.0
6,ME,167830.0,3796.0,2.261813,3222.0,632.0,1419.0,1852.0,406.0
29,DC,69250.0,2586.0,3.734296,1989.0,1334.0,399.0,985.0,178.0
30,VT,68688.0,1363.0,1.984335,1078.0,482.0,289.0,484.0,122.0
0,ND,80487.0,828.0,1.028738,NaN,NaN,NaN,NaN,NaN
1,PA,1586270.0,45980.0,2.898624,NaN,NaN,NaN,NaN,NaN
2,TX,2308662.0,32557.0,1.410211,NaN,NaN,NaN,NaN,NaN
4,MO,735070.0,14478.0,1.969608,NaN,NaN,NaN,NaN,NaN
5,CO,450894.0,11137.0,2.469982,NaN,NaN,NaN,NaN,NaN
7,OH,1415504.0,45503.0,3.214615,NaN,NaN,NaN,NaN,NaN
10,GA,969526.0,15538.0,1.602639,NaN,NaN,NaN,NaN,NaN
16,MT,118846.0,1477.0,1.242785,NaN,NaN,NaN,NaN,NaN
18,LA,526179.0,11393.0,2.165233,NaN,NaN,NaN,NaN,NaN
19,MI,1123841.0,24245.0,2.157334,NaN,NaN,NaN,NaN,NaN
21,TN,845502.0,18632.0,2.203661,NaN,NaN,NaN,NaN,NaN
22,ID,157810.0,2623.0,1.662125,NaN,NaN,NaN,NaN,NaN
23,CA,3139581.0,57154.0,1.820434,NaN,NaN,NaN,NaN,NaN
24,WY,52723.0,1138.0,2.158451,NaN,NaN,NaN,NaN,NaN
27,SD,94162.0,809.0,0.859158,NaN,NaN,NaN,NaN,NaN
28,AR,366574.0,4513.0,1.231129,NaN,NaN,NaN,NaN,NaN
31,DE,103860.0,2724.0,2.622761,NaN,NaN,NaN,NaN,NaN
32,IN,755967.0,16365.0,2.164777,NaN,NaN,NaN,NaN,NaN
36,IA,347398.0,3725.0,1.072257,NaN,NaN,NaN,NaN,NaN
38,AK,51141.0,1594.0,3.116873,NaN,NaN,NaN,NaN,NaN
39,NJ,846797.0,20055.0,2.368336,NaN,NaN,NaN,NaN,NaN
40,KY,559117.0,16155.0,2.889377,NaN,NaN,NaN,NaN,NaN
41,MS,369589.0,3933.0,1.064155,NaN,NaN,NaN,NaN,NaN
43,HI,131591.0,2294.0,1.743280,NaN,NaN,NaN,NaN,NaN
44,FL,2360692.0,48380.0,2.049399,NaN,NaN,NaN,NaN,NaN
45,IL,1240690.0,26227.0,2.113904,NaN,NaN,NaN,NaN,NaN
46,NE,196435.0,1425.0,0.725431,NaN,NaN,NaN,NaN,NaN
47,MN,512281.0,7668.0,1.496835,NaN,NaN,NaN,NaN,NaN
48,WI,612995.0,11926.0,1.945530,NaN,NaN,NaN,NaN,NaN
49,AZ,679217.0,16403.0,2.414987,NaN,NaN,NaN,NaN,NaN
50,AL,608611.0,8324.0,1.367704,NaN,NaN,NaN,NaN,NaN
51,MA,686740.0,23951.0,3.487637,NaN,NaN,NaN,NaN,NaN
52,KS,304518.0,3774.0,1.239336,NaN,NaN,NaN,NaN,NaN