In [7]:
# import dependencies
import pandas as pd
from sodapy import Socrata
import os
import requests
import googlemaps
from datetime import datetime
from config import gkey
import gmaps
import pymongo

# establish connection with Google Maps API
goog_maps = googlemaps.Client(key=gkey)

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
cms_client = Socrata("data.cms.gov", "zJczdf3uI6etj0TLR11GyFlB2")

In [8]:
cdc_client = Socrata("data.cdc.gov", "zJczdf3uI6etj0TLR11GyFlB2")

cdc_results = cdc_client.get("a3uk-kgrx", limit=2000000)

# Convert to pandas DataFrame
cdc_results_df = pd.DataFrame.from_records(cdc_results)

In [9]:
cdc_results_df

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
0,1411,NaN,Number of Drug Overdose Deaths,September,100,0.209391925847339,1468,NJ,NJ,2015
1,97.9872881355932,NaN,Percent with drugs specified,November,100,0.040500736377025,NaN,YC,YC,2015
2,6674,NaN,Number of Deaths,July,100,0.164818699430626,NaN,ND,ND,2016
3,64,NaN,Heroin (T40.1),January,100,0.0267343937976206,65,SC,SC,2015
4,684,NaN,"Opioids (T40.0-T40.4,T40.6)",May,100,0.00749105755004963,688,WA,WA,2015
5,11342,NaN,Number of Deaths,January,100,0.0440839358137895,NaN,NH,NH,2015
6,7899,NaN,Number of Deaths,July,100,0.063299151791366,NaN,SD,SD,2015
7,4358,NaN,Number of Drug Overdose Deaths,November,100,0.301462317210349,4608,PA,PA,2016
8,543,Underreported due to incomplete data,Number of Drug Overdose Deaths,January,100,0.0466789313270546,545,OR,OR,2018
9,2773,NaN,Number of Drug Overdose Deaths,November,100,0.173351234291652,2867,TX,TX,2016
10,1137,NaN,Number of Drug Overdose Deaths,March,100,0.005480352934729,1142,WA,WA,2016
11,54629,NaN,Number of Deaths,December,100,0.00549158871661572,NaN,WA,WA,2015
12,413,NaN,"Opioids (T40.0-T40.4,T40.6)",September,100,0.118895966029724,424,NH,NH,2015
13,61135,NaN,Number of Deaths,June,100,0.0245358632534555,NaN,MO,MO,2016
14,1796,NaN,Number of Drug Overdose Deaths,January,100,0.045028625340395,1816,MI,MI,2015
15,38075,NaN,Number of Deaths,November,100,0.0262639527248851,NaN,CO,CO,2016
16,95.4365079365079,Underreported due to incomplete data,Percent with drugs specified,January,100,0.0738794943359054,NaN,OR,OR,2017
17,67019,Underreported due to incomplete data,Number of Deaths,August,100,0.0373028544144198,NaN,VA,VA,2017
18,51,NaN,Cocaine (T40.5),July,100,0,53,ME,ME,2016
19,29667,NaN,Number of Deaths,August,100,0.010112245929821,NaN,IA,IA,2015
20,3398,NaN,Number of Drug Overdose Deaths,January,100,0.0256344527044348,3425,OH,OH,2016
21,7028,NaN,Number of Deaths,September,100,0.284575981787137,NaN,ND,ND,2015
22,354,NaN,Natural & semi-synthetic opioids (T40.2),July,100,0.0558743257473191,360,SC,SC,2016
23,40,NaN,"Synthetic opioids, excl. methadone (T40.4)",September,100,0.0590767153346274,41,OR,OR,2016
24,5777,NaN,Psychostimulants with abuse potential (T43.6),December,100,0.153226512564574,6008,US,US,2015
25,220,Underreported due to incomplete data,Natural & semi-synthetic opioids (T40.2),February,100,0,221,NV,NV,2017
26,449,NaN,Number of Drug Overdose Deaths,October,100,0.12709710218607,461,NH,NH,2015
27,1723,NaN,Number of Drug Overdose Deaths,December,100,0.813464712989908,2005,MA,MA,2015
28,63,NaN,Methadone (T40.3),September,100,0.0183040033470178,64,OK,OK,2015
29,62,NaN,"Synthetic opioids, excl. methadone (T40.4)",February,100,0.338477425276806,67,UT,UT,2015
...,...,...,...,...,...,...,...,...,...,...
10344,102,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.00509087206638497,103,OK,OK,2017
10345,14,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),November,100,0.0159821000479463,15,DC,DC,2017
10346,18360,Underreported due to incomplete data,Number of Deaths,August,100,0.669934640522876,NaN,UT,UT,2017
10347,677,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.0190918636840933,685,CT,CT,2017
10348,406,Underreported due to incomplete data,"Opioids (T40.0-T40.4,T40.6)",May,100,0.0661047760700711,411,NH,NH,2017
10349,38236,Underreported due to incomplete data,Number of Deaths,January,100,0.0313840359870279,NaN,CO,CO,2017
10350,106,Underreported due to incomplete data,Cocaine (T40.5),February,100,0.192086054552439,110,RI,RI,2018
10351,429,Underreported due to incomplete data,"Opioids (T40.0-T40.4,T40.6)",November,100,0.024358557973368,434,NH,NH,2017
10352,349,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),February,100,0.0320907097395304,353,WA,WA,2017
10353,2640,Underreported due to incomplete data,Number of Drug Overdose Deaths,January,100,0.0816351837308312,2665,MI,MI,2018
10354,243,Underreported due to incomplete data,Heroin (T40.1),February,100,0.152973994420948,249,WV,WV,2017
10355,31,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),September,100,0.0158503724837534,32,CT,CT,2017
10356,140,Underreported due to incomplete data,Heroin (T40.1),January,100,0.176347404386642,144,NM,NM,2018
10357,99673,Underreported due to incomplete data,Number of Deaths,August,100,0.492610837438424,NaN,NY,NY,2017
10358,1629,Underreported due to incomplete data,Number of Drug Overdose Deaths,February,100,0.00771807418612908,1630,IN,IN,2017
10359,79,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",April,100,0.0674498341858243,81,NM,NM,2017
10360,64,Underreported due to incomplete data,"Synthetic opioids, excl. methadone (T40.4)",November,100,0.0352057580973244,65,NV,NV,2017
10361,12,Underreported due to incomplete data,Methadone (T40.3),January,100,0.0161851582099215,12,NH,NH,2018
10362,10101,Underreported due to incomplete data,Number of Deaths,February,100,0.0297000297000297,NaN,MT,MT,2018
10363,99.4623655913979,Underreported due to incomplete data,Percent with drugs specified,May,100,0.0184522271838211,NaN,YC,YC,2017
10364,1060,Underreported due to incomplete data,Number of Drug Overdose Deaths,July,100,0.0587418562426573,1077,WA,WA,2017
10365,267350,Underreported due to incomplete data,Number of Deaths,August,100,0.35459135964092,NaN,CA,CA,2017
10366,286,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),May,100,0.00517022981671535,287,OK,OK,2017
10367,94.5397815912636,Underreported due to incomplete data,Percent with drugs specified,January,100,0.888434202024553,NaN,UT,UT,2017
10368,95.9016393442623,Underreported due to incomplete data,Percent with drugs specified,February,100,0.0150138878462578,NaN,OK,OK,2018
10369,9,Underreported due to incomplete data,Psychostimulants with abuse potential (T43.6),September,100,0,10,VT,VT,2017
10370,48,Underreported due to incomplete data,Methadone (T40.3),February,100,0.202095410306866,50,UT,UT,2018
10371,6227,Underreported due to incomplete data,Number of Deaths,March,100,0,NaN,DC,DC,2017
10372,542,Underreported due to incomplete data,Cocaine (T40.5),February,100,0.0386008124551955,559,YC,YC,2017
10373,1083,Underreported due to incomplete data,Number of Drug Overdose Deaths,September,100,0.0158503724837534,1096,CT,CT,2017

In [10]:
print(cdc_results_df["indicator"].unique())

['Number of Drug Overdose Deaths' 'Percent with drugs specified'
 'Number of Deaths' 'Heroin (T40.1)' 'Opioids (T40.0-T40.4,T40.6)'
 'Cocaine (T40.5)' 'Natural & semi-synthetic opioids (T40.2)'
 'Synthetic opioids, excl. methadone (T40.4)'
 'Psychostimulants with abuse potential (T43.6)' 'Methadone (T40.3)']

In [15]:
overdoses_2016_df = cdc_results_df.loc[cdc_results_df["year"] == "2016", :]

overdoses_2016_df.head()

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
2,6674,NaN,Number of Deaths,July,100,0.164818699430626,NaN,ND,ND,2016
7,4358,NaN,Number of Drug Overdose Deaths,November,100,0.301462317210349,4608,PA,PA,2016
9,2773,NaN,Number of Drug Overdose Deaths,November,100,0.173351234291652,2867,TX,TX,2016
10,1137,NaN,Number of Drug Overdose Deaths,March,100,0.005480352934729,1142,WA,WA,2016
13,61135,NaN,Number of Deaths,June,100,0.0245358632534555,NaN,MO,MO,2016

In [16]:
January_cdc_df = overdoses_2016_df.loc[cdc_results_df["month"] == "January", :]

January_cdc_df

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
20,3398,NaN,Number of Drug Overdose Deaths,January,100,0.0256344527044348,3425,OH,OH,2016
60,381,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.33683265031157,412,UT,UT,2016
68,45,NaN,Psychostimulants with abuse potential (T43.6),January,100,0.408054734559884,50,NY,NY,2016
75,72,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0.33683265031157,78,UT,UT,2016
103,8485,NaN,Number of Deaths,January,100,0,NaN,DE,DE,2016
152,338,NaN,"Opioids (T40.0-T40.4,T40.6)",January,100,0.0941896744569377,346,NM,NM,2016
203,65,NaN,Methadone (T40.3),January,100,0.0225206204430932,66,OR,OR,2016
213,94.1472624292008,NaN,Percent with drugs specified,January,100,0.249933053646345,NaN,NC,NC,2016
236,180,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.0164646996838778,182,CT,CT,2016
277,46,NaN,Cocaine (T40.5),January,100,0.33683265031157,49,UT,UT,2016
279,37,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0.00424232139826913,38,NV,NV,2016
291,174,NaN,Number of Drug Overdose Deaths,January,100,0.00903342366757001,175,HI,HI,2016
345,303,NaN,Number of Drug Overdose Deaths,January,100,0.00344459371017189,305,IA,IA,2016
426,93137,NaN,Number of Deaths,January,100,0.0343579887692324,NaN,MI,MI,2016
453,96.8287526427061,NaN,Percent with drugs specified,January,100,0.0941896744569377,NaN,NM,NM,2016
455,12729,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.150668764023293,13200,US,US,2016
458,1228,NaN,Number of Drug Overdose Deaths,January,100,0.0175690784219773,1236,IN,IN,2016
518,1840,NaN,Number of Drug Overdose Deaths,January,100,0.408054734559884,1983,NY,NY,2016
524,98.5418265541059,NaN,Percent with drugs specified,January,100,0.0214523222138797,NaN,MD,MD,2016
613,403,NaN,Heroin (T40.1),January,100,0.0164646996838778,405,CT,CT,2016
641,4745,NaN,Number of Drug Overdose Deaths,January,100,0.359810723362244,5070,CA,CA,2016
714,149,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0.0628767182689389,153,SC,SC,2016
742,5616,NaN,Number of Deaths,January,100,0.106837606837607,NaN,DC,DC,2016
805,343,NaN,Cocaine (T40.5),January,100,0.249933053646345,358,NC,NC,2016
807,4213,NaN,Number of Deaths,January,100,0,NaN,AK,AK,2016
826,386,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0.0214523222138797,391,MD,MD,2016
831,9,NaN,Methadone (T40.3),January,100,0,9,VT,VT,2016
857,193,NaN,Psychostimulants with abuse potential (T43.6),January,100,0.00424232139826913,195,NV,NV,2016
858,3276,NaN,Methadone (T40.3),January,100,0.150668764023293,3383,US,US,2016
863,320,NaN,Number of Drug Overdose Deaths,January,100,0,322,RI,RI,2016
...,...,...,...,...,...,...,...,...,...,...
6508,7,NaN,Psychostimulants with abuse potential (T43.6),January,100,0,8,RI,RI,2016
6514,61,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.0946888181113885,63,NH,NH,2016
6582,106,NaN,Methadone (T40.3),January,100,0.249933053646345,112,NC,NC,2016
6597,272,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.00424232139826913,274,NV,NV,2016
6625,35523,NaN,Number of Deaths,January,100,0.0225206204430932,NaN,OR,OR,2016
6626,69729,NaN,Number of Deaths,January,100,0.293995324757275,NaN,TN,TN,2016
6630,6,NaN,Psychostimulants with abuse potential (T43.6),January,100,0.0946888181113885,7,NH,NH,2016
6636,33,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0,34,VT,VT,2016
6642,50651,NaN,Number of Deaths,January,100,0.209275236421788,NaN,WI,WI,2016
6667,84,NaN,Heroin (T40.1),January,100,0.106837606837607,86,DC,DC,2016
6682,356,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.141275121906758,369,WV,WV,2016
6728,44,NaN,Cocaine (T40.5),January,100,0.0941896744569377,46,NM,NM,2016
6747,199,NaN,Heroin (T40.1),January,100,0.141275121906758,204,WV,WV,2016
6758,31049,NaN,Number of Deaths,January,100,0.0161035782150794,NaN,MS,MS,2016
6778,49,NaN,Psychostimulants with abuse potential (T43.6),January,100,0.0391615694465165,50,YC,YC,2016
6787,33531,NaN,"Opioids (T40.0-T40.4,T40.6)",January,100,0.150668764023293,34606,US,US,2016
6832,34,NaN,Methadone (T40.3),January,100,0,34,ME,ME,2016
6846,271,NaN,Natural & semi-synthetic opioids (T40.2),January,100,0.0296708101692798,275,VA,VA,2016
6858,125,NaN,Methadone (T40.3),January,100,0.0391615694465165,126,YC,YC,2016
6862,99.5896032831737,NaN,Percent with drugs specified,January,100,0.141275121906758,NaN,WV,WV,2016
6868,270,NaN,Number of Drug Overdose Deaths,January,100,0,271,ME,ME,2016
6892,731,NaN,Number of Drug Overdose Deaths,January,100,0.141275121906758,752,WV,WV,2016
6895,154,NaN,"Synthetic opioids, excl. methadone (T40.4)",January,100,0.0391615694465165,157,YC,YC,2016
6940,29031,NaN,Number of Deaths,January,100,0.00344459371017189,NaN,IA,IA,2016
6946,7793,NaN,Number of Deaths,January,100,0.0256640574874888,NaN,SD,SD,2016
6975,96,NaN,Heroin (T40.1),January,100,0.0628767182689389,98,SC,SC,2016
6989,98.3101391650099,NaN,Percent with drugs specified,January,100,0.0296708101692798,NaN,VA,VA,2016
7007,3269,NaN,Number of Drug Overdose Deaths,January,100,0.265961465810351,3435,PA,PA,2016
7052,62,NaN,Number of Drug Overdose Deaths,January,100,0.148060408646728,64,ND,ND,2016
7104,890,NaN,Number of Drug Overdose Deaths,January,100,0.0827681342683067,906,LA,LA,2016

In [18]:
Ma_January_cdc_df = overdoses_2016_df.loc[cdc_results_df["state_name"] == "MA", :]

Ma_January_cdc_df

,data_value,footnote,indicator,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
738,56793,NaN,Number of Deaths,July,100,0.392654024263554,NaN,MA,MA,2016
1014,2143,NaN,Number of Drug Overdose Deaths,October,100,0.369701960646891,2294,MA,MA,2016
1153,2073,NaN,Number of Drug Overdose Deaths,July,100,0.392654024263554,2228,MA,MA,2016
1417,57469,NaN,Number of Deaths,February,100,0.676886669334772,NaN,MA,MA,2016
1560,2089,NaN,Number of Drug Overdose Deaths,August,100,0.391358523016444,2245,MA,MA,2016
2013,2001,NaN,Number of Drug Overdose Deaths,June,100,0.447863427999368,2173,MA,MA,2016
2044,57861,NaN,Number of Deaths,December,100,0.480461796374069,NaN,MA,MA,2016
3038,1738,NaN,Number of Drug Overdose Deaths,January,100,0.749904965960535,1997,MA,MA,2016
3070,57250,NaN,Number of Deaths,March,100,0.646288209606987,NaN,MA,MA,2016
3186,1932,NaN,Number of Drug Overdose Deaths,May,100,0.526925914216461,2128,MA,MA,2016
3818,57129,NaN,Number of Deaths,September,100,0.385093385145898,NaN,MA,MA,2016
3943,2198,NaN,Number of Drug Overdose Deaths,December,100,0.480461796374069,2401,MA,MA,2016
4108,56981,NaN,Number of Deaths,August,100,0.391358523016444,NaN,MA,MA,2016
4217,57362,NaN,Number of Deaths,November,100,0.453261741222412,NaN,MA,MA,2016
4446,57073,NaN,Number of Deaths,October,100,0.369701960646891,NaN,MA,MA,2016
4609,1889,NaN,Number of Drug Overdose Deaths,April,100,0.572910279096659,2099,MA,MA,2016
4629,56934,NaN,Number of Deaths,May,100,0.526925914216461,NaN,MA,MA,2016
4792,56937,NaN,Number of Deaths,June,100,0.447863427999368,NaN,MA,MA,2016
5048,57077,NaN,Number of Deaths,April,100,0.572910279096659,NaN,MA,MA,2016
5481,1812,NaN,Number of Drug Overdose Deaths,March,100,0.646288209606987,2041,MA,MA,2016
5913,2157,NaN,Number of Drug Overdose Deaths,November,100,0.453261741222412,2344,MA,MA,2016
6170,57874,NaN,Number of Deaths,January,100,0.749904965960535,NaN,MA,MA,2016
6448,1788,NaN,Number of Drug Overdose Deaths,February,100,0.676886669334772,2026,MA,MA,2016
6739,2131,NaN,Number of Drug Overdose Deaths,September,100,0.385093385145898,2287,MA,MA,2016

In [61]:
MA = Ma_January_cdc_df[["data_value", "indicator"]]

In [62]:
MA["data_value"] = MA["data_value"].astype(float)

/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [63]:
MA_data = Ma_January_cdc_df.groupby("indicator").sum()

MA_data

,data_value,footnote,month,percent_complete,percent_pending_investigation,predicted_value,state,state_name,year
indicator,,,,,,,,,
Number of Deaths,5679357469578615725057129569815736257073569345...,0,JulyFebruaryDecemberMarchSeptemberAugustNovemb...,100100100100100100100100100100100100,0.3926540242635540.6768866693347720.4804617963...,0,MAMAMAMAMAMAMAMAMAMAMAMA,MAMAMAMAMAMAMAMAMAMAMAMA,201620162016201620162016201620162016201620162016
Number of Drug Overdose Deaths,214320732089200117381932219818891812215717882131,0,OctoberJulyAugustJuneJanuaryMayDecemberAprilMa...,100100100100100100100100100100100100,0.3697019606468910.3926540242635540.3913585230...,229422282245217319972128240120992041234420262287,MAMAMAMAMAMAMAMAMAMAMAMA,MAMAMAMAMAMAMAMAMAMAMAMA,201620162016201620162016201620162016201620162016

In [22]:
state = overdoses_2016_df.groupby('state_name')

state

In [43]:
opioids_cdc_df = cdc_results_df.loc[cdc_results_df["indicator"].isin(["Opioids (T40.0-T40.4,T40.6)", "Heroin (T40.1)", "Natural & semi-synthetic opioids (T40.2)", "Synthetic opioids, excl. methadone (T40.4)", "Methadone (T40.3)"]), :]

In [47]:
opioids_by_state = opioids_cdc_df[["data_value", "state"]]

In [48]:
opioids_by_state["data_value"] = opioids_by_state["data_value"].astype(float)

/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [49]:
state = opioids_by_state.groupby("state").sum()

state

       data_value
state
CT        72786.0
DC        17760.0
MD       142802.0
ME        24866.0
NC       123096.0
NH        33345.0
NM        30595.0
NV        33886.0
NY       155272.0
OK        34997.0
OR        26438.0
RI        23216.0
SC        52193.0
US      3392897.0
UT        41465.0
VA        88880.0
VT         8362.0
WA        58510.0
WV        65670.0
YC        88924.0

In [54]:
#state_df = state.loc[state["state"] == "NH" :]

Ma_January_cdc_df = state.loc[state["state_name"] == "MA", :]

KeyError: 'state_name'

In [ ]:
opioids_cdc_df = cdc_results_df.loc[cdc_results_df["indicator"] == "Opioids (T40.0-T40.4,T40.6)"]

In [32]:
grouped_df = opioids_by_state.groupby("state_name")

for key, item in grouped_df:
    print(grouped_df.get_group(key), "\n\n")

      data_value state_name
180          874         CT
456          660         CT
568          686         CT
1398         683         CT
1533         553         CT
1643         814         CT
1874         878         CT
2258         550         CT
2965         825         CT
3316         536         CT
3416         832         CT
3563         711         CT
3636         567         CT
3769         618         CT
4612         810         CT
4929         532         CT
4984         800         CT
5124         530         CT
5210         616         CT
5491         766         CT
5672         741         CT
5678         869         CT
6058         795         CT
6293         633         CT
6445         731         CT
7049         834         CT
7639         967         CT
7648         905         CT
8092         945         CT
8130         979         CT
8217         967         CT
8775         926         CT
9087         959         CT
9317         965         CT
9546         939         CT
9579         940         CT
9946         940         CT
10233        903         CT
10267        968         CT


      data_value state_name
48            80         DC
595           83         DC
694          113         DC
1010         135         DC
1034          82         DC
1463          80         DC
2227          80         DC
2354         155         DC
3029          83         DC
3246         124         DC
3526          80         DC
3759         195         DC
3972         230         DC
3980         163         DC
3990         221         DC
4158         187         DC
4208         170         DC
4915          92         DC
5479         102         DC
5668          81         DC
6187         115         DC
6220          95         DC
6222         181         DC
6685         112         DC
7115         305         DC
7744         244         DC
7761         268         DC
7917         290         DC
7970         303         DC
7990         271         DC
8339         300         DC
8501         253         DC
8786         253         DC
8848         220         DC
8853         304         DC
9135         305         DC
10179        298         DC
10208        271         DC
10241        286         DC


      data_value state_name
288         1389         MD
540         1150         MD
719         1866         MD
1206        1201         MD
1291         975         MD
1575        1286         MD
1829        1033         MD
2116        1491         MD
2461         970         MD
2547        1561         MD
2627         936         MD
2947        1954         MD
2958        1640         MD
3145        1733         MD
4080         969         MD
4301        1795         MD
4315        1096         MD
5140         996         MD
5367        1694         MD
5384         965         MD
5572         964         MD
5892        1130         MD
6251        1112         MD
6579         976         MD
6957        1071         MD
7527        2027         MD
7612        2020         MD
7875        2040         MD
8048        2037         MD
8081        2037         MD
8180        2037         MD
9034        2100         MD
9137        2038         MD
9341        2011         MD
9403        2140         MD
9604        2039         MD
9663        2002         MD
10204       1967         MD
10303       2038         MD


      data_value state_name
664          257         ME
1421         290         ME
1703         291         ME
1805         288         ME
1905         241         ME
2613         324         ME
2806         171         ME
2820         208         ME
3041         211         ME
3435         181         ME
3523         315         ME
3716         232         ME
4047         284         ME
4051         235         ME
4436         283         ME
4498         235         ME
4728         273         ME
5236         316         ME
5280         316         ME
5790         306         ME
5847         319         ME
6028         196         ME
6411         232         ME
6525         237         ME
6527         219         ME
7019         223         ME
7039         209         ME
7077         237         ME
7100         246         ME
7134         349         ME
7806         311         ME
7935         340         ME
8384         323         ME
8608         348         ME
9185         339         ME
9750         345         ME
9896         310         ME
10293        350         ME
10329        314         ME


     data_value state_name
838         979         NC
878        1398         NC
1096       1059         NC
1201       1310         NC
1907       1061         NC
2383       1444         NC
2623        986         NC
2924       1361         NC
3211       1497         NC
3544       1468         NC
4132       1131         NC
4461       1252         NC
4895       1456         NC
5005       1159         NC
5259       1212         NC
5446       1074         NC
5711       1046         NC
5902       1199         NC
6091       1020         NC
6314       1278         NC
6614       1468         NC
6876       1002         NC
6889       1038         NC
6969       1090         NC
7246       1741         NC
7273       1916         NC
7368       1711         NC
7378       1608         NC
7401       1546         NC
7450       1669         NC
7715       1870         NC
7738       1875         NC
7856       1810         NC
8121       1943         NC
8150       1639         NC
8624       1830         NC
8774       1890         NC
9267       1901         NC
9709       1584         NC


      data_value state_name
12           413         NH
136          356         NH
237          412         NH
323          365         NH
560          388         NH
658          415         NH
707          378         NH
1133         397         NH
1448         389         NH
1467         317         NH
1677         376         NH
1828         378         NH
1927         325         NH
4002         330         NH
4077         393         NH
4225         407         NH
4591         384         NH
4634         403         NH
4811         400         NH
5057         389         NH
5443         400         NH
5720         400         NH
6087         398         NH
6944         399         NH
7459         422         NH
7513         417         NH
7667         432         NH
7881         406         NH
8237         433         NH
8371         395         NH
8447         435         NH
8483         430         NH
8954         429         NH
9218         434         NH
9680         414         NH
9781         433         NH
9870         404         NH
10348        406         NH
10351        429         NH


      data_value state_name
152          338         NM
250          339         NM
367          380         NM
929          405         NM
1361         366         NM
2121         378         NM
2207         354         NM
2250         350         NM
2389         403         NM
2469         363         NM
2566         380         NM
2654         413         NM
2661         354         NM
2911         363         NM
3473         376         NM
3702         358         NM
3717         375         NM
4306         353         NM
4323         347         NM
4435         388         NM
4881         349         NM
5453         347         NM
5562         369         NM
6864         356         NM
7147         321         NM
7436         358         NM
8142         351         NM
8272         325         NM
8279         336         NM
8475         361         NM
8641         355         NM
8829         328         NM
9264         342         NM
9282         354         NM
9332         351         NM
9397         343         NM
9800         359         NM
10205        336         NM
10271        353         NM


      data_value state_name
42           454         NV
54           454         NV
705          428         NV
996          383         NV
1350         427         NV
1515         411         NV
1718         406         NV
1820         451         NV
1853         397         NV
1870         390         NV
2367         446         NV
2369         394         NV
2673         444         NV
3887         424         NV
3934         456         NV
3961         454         NV
3999         443         NV
4234         412         NV
4578         423         NV
4707         422         NV
5613         446         NV
6167         459         NV
6604         444         NV
6620         383         NV
6792         423         NV
6804         460         NV
7227         420         NV
7481         423         NV
8009         444         NV
8116         411         NV
8859         437         NV
9122         423         NV
9233         433         NV
9270         414         NV
9692         419         NV
9756         420         NV
9918         414         NV
9932         421         NV
10124        417         NV


     data_value state_name
33         1198         NY
947        1499         NY
1222       1621         NY
1641       1310         NY
1800       1928         NY
1970       1673         NY
2485       1445         NY
2490       1785         NY
2492       1178         NY
2632       1413         NY
2756       1713         NY
2937       1813         NY
3072       1571         NY
3299       1854         NY
3354       1348         NY
4494       1285         NY
5206       1644         NY
5456       1257         NY
5570       1752         NY
5906       1384         NY
5925       1172         NY
5951       1452         NY
6279       1413         NY
6531       1880         NY
7117       2127         NY
7136       2092         NY
7138       1995         NY
7753       1912         NY
7995       2056         NY
8000       2115         NY
8400       2007         NY
8504       2152         NY
8835       2129         NY
8946       1956         NY
9116       2080         NY
9480       2062         NY
9538       2096         NY
9722       1958         NY
9961       1999         NY


     data_value state_name
32          470         OK
217         444         OK
1033        425         OK
1389        432         OK
2075        482         OK
2083        432         OK
2084        418         OK
2585        411         OK
2736        431         OK
3112        411         OK
3584        492         OK
3655        410         OK
3842        401         OK
3909        487         OK
3933        420         OK
4015        505         OK
4411        434         OK
4952        414         OK
5051        425         OK
5732        409         OK
5877        427         OK
5915        420         OK
5931        463         OK
6044        496         OK
7316        424         OK
7407        387         OK
7440        446         OK
7451        428         OK
7488        450         OK
7627        376         OK
7693        448         OK
7895        402         OK
8040        351         OK
8151        438         OK
8701        452         OK
9049        448         OK
9234        401         OK
9517        344         OK
9605        447         OK


     data_value state_name
384         337         OR
450         333         OR
498         306         OR
825         328         OR
941         326         OR
1172        335         OR
1289        339         OR
1394        329         OR
1621        339         OR
1661        317         OR
1773        344         OR
2151        303         OR
2477        330         OR
2631        314         OR
2800        330         OR
3196        350         OR
3271        315         OR
3331        344         OR
3484        340         OR
3696        347         OR
4297        313         OR
4347        311         OR
4348        323         OR
4536        316         OR
5131        341         OR
5314        310         OR
5322        335         OR
5439        331         OR
5478        343         OR
5640        306         OR
5763        310         OR
6015        340         OR
6418        351         OR
6546        344         OR
6560        309         OR
6910        332         OR
6970        323         OR
7017        325         OR
8532        342         OR


      data_value state_name
72           277         RI
181          297         RI
593          300         RI
1512         272         RI
1770         283         RI
1961         218         RI
1981         268         RI
1984         273         RI
2056         274         RI
2245         260         RI
2265         282         RI
2341         278         RI
2584         214         RI
3841         279         RI
4069         264         RI
4683         221         RI
4911         278         RI
5277         221         RI
5344         279         RI
5536         251         RI
5619         267         RI
5807         235         RI
5817         268         RI
6055         264         RI
6497         294         RI
7132         280         RI
7704         290         RI
7816         299         RI
7934         284         RI
8191         274         RI
8417         296         RI
8478         280         RI
8584         288         RI
8703         263         RI
8794         282         RI
9357         269         RI
9484         285         RI
9619         284         RI
10068        280         RI


      data_value state_name
320          526         SC
1054         530         SC
1178         508         SC
1208         566         SC
1230         529         SC
1567         586         SC
2065         549         SC
2197         538         SC
2722         584         SC
3447         537         SC
3892         534         SC
4021         540         SC
4053         599         SC
4263         613         SC
4553         533         SC
4775         591         SC
4843         582         SC
4935         553         SC
4948         542         SC
4981         544         SC
5466         581         SC
5744         552         SC
6943         514         SC
7044         559         SC
7211         771         SC
7261         754         SC
7393         635         SC
7870         754         SC
8241         698         SC
8431         747         SC
8459         654         SC
8528         737         SC
8808         647         SC
8883         732         SC
9337         732         SC
9390         659         SC
9930         681         SC
10270        760         SC
10335        700         SC


      data_value state_name
183        30745         US
1016       35062         US
2096       30240         US
2130       34251         US
2161       29269         US
2268       33040         US
2346       41126         US
2372       28986         US
3118       37187         US
3245       42435         US
3601       33203         US
3707       38856         US
3813       35837         US
3885       38075         US
4314       39437         US
4318       32775         US
5235       31392         US
5341       31767         US
5749       29609         US
5750       36423         US
5894       32337         US
6185       31068         US
6757       40149         US
6787       33531         US
7238       45897         US
7711       47198         US
8018       47944         US
8072       44791         US
8665       47474         US
8754       47936         US
8937       47014         US
9302       46655         US
9394       47851         US
9454       47702         US
9662       46478         US
9732       46789         US
9912       45248         US
10292      44282         US
10302      43692         US


      data_value state_name
538          501         UT
1670         473         UT
2251         490         UT
2471         438         UT
2606         451         UT
2638         512         UT
2676         436         UT
3304         445         UT
3365         443         UT
3871         442         UT
4595         509         UT
5069         435         UT
5165         514         UT
5298         457         UT
5642         506         UT
5700         503         UT
5760         496         UT
6188         521         UT
6313         464         UT
6536         456         UT
6613         475         UT
6643         433         UT
6711         433         UT
6811         505         UT
7118         467         UT
7121         439         UT
7233         445         UT
7571         437         UT
7921         449         UT
8028         449         UT
8170         430         UT
8650         466         UT
8783         430         UT
8819         440         UT
9237         449         UT
9410         456         UT
9790         437         UT
10002        432         UT
10048        452         UT


     data_value state_name
56         1150         VA
93          767         VA
865        1170         VA
1327        804         VA
1416       1056         VA
1486       1188         VA
1709       1117         VA
1784       1097         VA
1934       1028         VA
2004        926         VA
2021        951         VA
2246        751         VA
2798       1009         VA
3026        976         VA
3724        748         VA
3755        771         VA
4032       1151         VA
4354        812         VA
4533       1140         VA
4555       1169         VA
4623       1148         VA
4863        902         VA
4963       1180         VA
4964       1146         VA
5764        794         VA
5842        763         VA
6255        793         VA
6267        855         VA
6291       1161         VA
6377        994         VA
6422       1190         VA
6439        754         VA
6454       1198         VA
6645        802         VA
6656       1146         VA
6993        760         VA
7018        780         VA
8198       1162         VA
8653       1159         VA


      data_value state_name
403           87         VT
419           58         VT
462           58         VT
475          112         VT
501          114         VT
899           74         VT
1109          66         VT
1161          72         VT
1395          79         VT
1427          84         VT
1586         107         VT
1757          80         VT
1899          79         VT
1989         116         VT
2431         109         VT
2887         111         VT
3077          76         VT
3395          84         VT
3856          83         VT
4257         100         VT
4450          91         VT
4855          83         VT
4936         110         VT
5054         112         VT
5285         109         VT
5569          62         VT
5589          94         VT
6299          79         VT
6447          84         VT
6762         115         VT
6844         102         VT
6950         110         VT
6967          77         VT
6987          70         VT
7152         110         VT
7221         108         VT
8368         115         VT
8791         106         VT
10187        104         VT


      data_value state_name
4            684         WA
107          725         WA
873          750         WA
925          694         WA
1237         686         WA
1523         674         WA
1566         691         WA
1645         766         WA
1901         721         WA
2159         758         WA
2185         721         WA
2447         705         WA
2559         704         WA
2611         704         WA
3226         742         WA
4191         691         WA
4701         678         WA
5149         751         WA
5241         683         WA
5253         702         WA
5370         722         WA
6066         768         WA
6443         748         WA
6951         722         WA
7381         668         WA
7518         709         WA
8005         743         WA
8135         670         WA
8358         729         WA
8419         707         WA
8502         695         WA
8805         690         WA
8932         722         WA
9563         690         WA
9641         676         WA
9909         749         WA
10040        753         WA
10144        728         WA
10300        705         WA



In [31]:
state.describe()

           data_value
                count unique    top freq
state_name
CT                 39     37    967    2
DC                 39     32     80    4
MD                 39     36   2037    3
ME                 39     35    232    2
NC                 39     38   1468    2
NH                 39     32    400    3
NM                 39     30    354    3
NV                 39     27    423    4
NY                 39     38   1413    2
OK                 39     33    425    2
OR                 39     30    344    3
RI                 39     29    280    3
SC                 39     37    732    2
US                 39     39  35062    1
UT                 39     32    449    3
VA                 39     38   1146    2
VT                 39     28     79    3
WA                 39     32    722    3
WV                 39     36    653    2
YC                 39     37    596    2

In [ ]:
'Heroin (T40.1)' 'Opioids (T40.0-T40.4,T40.6)'
'Cocaine (T40.5)' 'Natural & semi-synthetic opioids (T40.2)'
 'Synthetic opioids, excl. methadone (T40.4)'
 'Psychostimulants with abuse potential (T43.6)' 'Methadone (T40.3)']